language: node_js
node_js:
  - 14
scripts:
  - eslint 'src/**'
  - npm run test:coveralls
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  on:
    all_branches: true
  app: clean-typescript-api
  skip_cleanup: true
